---
- name: create the www root directy
  file:
    path: "{{ app_deploy_directory }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  become: yes
  become_user: root

# we download the repo as the root user in order to maintain our ssh-agent key forwarding. This is a bit of a flaw
# with ansible in general...
- name: download the repo
  git:
    repo: "{{ app_github_repo }}"
    dest: "{{ app_deploy_directory }}"
    version: "{{ app_branch_name | default('master') }}"
    force: yes
    accept_hostkey: yes

# copy over our template files to the appropriate directories
- name: create our .env files for the project
  template:
    src: "{{ ansible_inventory_sources[0] }}/templates/.env.j2"
    dest: "{{ app_deploy_directory }}/.env"
    owner: ubuntu
    group: ubuntu
    mode: '0666'
  become: yes
  become_user: root

- name: Install jupyter
  apt:
    name: jupyter-notebook
    state: present
  become: true

- name: Install datascience requirements
  pip:
    executable: /usr/bin/pip3
    requirements: "{{ app_deploy_directory }}/requirements.txt"

- name: Add jupyter notebooks directory
  file: 
    path: /etc/jupyter/notebooks
    state: directory
  become: true

- name: Add jupyter config
  template:
    src: jupyter_notebook_config.json.j2
    dest: /etc/jupyter/jupyter_notebook_config.json
  become: true
  notify: restart_jupyter

- name: Create the jupyter service
  template:
    src: jupyter.service.j2
    dest: /etc/systemd/system/jupyter.service
  become: true
  notify: restart_jupyter

- name: Start and enable the service, reload the daemon
  systemd:
    name: jupyter
    state: started
    enabled: true
    daemon_reload: true
  become: true
