---
- name: golden images
  hosts: localhost
  become: true
  connection: local
  roles:
    - system/common
    - system/users
    - service/github
    - service/supervisor
    - system/mobica-server-config
